[project]
name = "pretrained-models"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "torch>=2.4.1",
    "torchvision>=0.19.1",
    "safetensors>=0.4.5",
]
